### ISSUE TITLE
The given name for the accesstoken is not unique

### ISSUE THREAD

**Issue by IHateNameStealers** [victronenergy/dynamic-ess#10]
After creating a valid Bearer token, I get an "error" on "Create an access token for a user" when using the generated Bearer token and user idUser.

I'm 100% sure that I use the complete (long) generated token, and idUser.

```
{
  "success": false,
  "error_code": "validation_error",
  "errors": {
    "name": "The given name for the accesstoken is not unique"
  }
}
```

Any help appreciated.

**Comment by dirkjanfaber** [comment]
The easiest way is to go to https://vrm.victronenergy.com/access-tokens instead for creating the access token. I'll add that to the documentation too, as that is much easier than the currently documented way.

**Comment by IHateNameStealers** [comment]
Dankjewel.
