### ISSUE TITLE
[VRM - Bug]: Battery is at the evening not at 100 % and next day I have to buy with higher costs

### ISSUE THREAD

**Issue by pokeplayer2** [victronenergy/dynamic-ess#104]
### VRM portal ID

b827eb6ff17f

### Country / region

Germany (de)

### B max

26

### TB max

6,5

### FB max

7

### TG max

30

### FG max

30

### Battery costs

0,02

### Buy price

p+0.217+0.0161

### Sell price

0,115

### feed-in possible

yes

### feed-in control

yes

### What happened?

At the evening is the battery not at 100% end I will have to by power next day for a higher price :-/ 

### When did it happen?

15/10/2023 15:01 I have manual change to from auto mode to buy mode.

### Screenshots

![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/bc40df5e-9438-49e7-aa5f-5c8d03dfafcc)

price overvview for 15/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/e9c8ecb5-30e1-478f-85c9-fa527b49097f)

price overview for 16/10/2023
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/9510a883-e7c1-415f-a282-3f9ef2873235)

fill the battery to 100% is much better ;-)

**Comment by dirkjanfaber** [comment]
Thing is the moment DESS knew about this (which is 15:00) it would have charged, but you jumped the gun and decided to turn on Sell prices at 15:01, right after checking it yourself. It might be that Dynamic ESS showed something different (at the very start of the hour), but we are pretty sure you were just impatient here.
