### ISSUE TITLE
[VRM - Bug]: Tibber Price from Germany is not 100% correct

### ISSUE THREAD

**Issue by pokeplayer2** [victronenergy/dynamic-ess#109]
### VRM portal ID

b827eb6ff17f

### Country / region

Germany (de)

### B max

26

### TB max

6,5

### FB max

7

### TG max

30

### FG max

30

### Battery costs

0,02

### Buy price

p+0.21*1.19

### Sell price

0,115

### feed-in possible

yes

### feed-in control

yes

### What happened?

Buy price is wrong

### When did it happen?

19/10/203 20:25

### Screenshots
Tibber Germany
![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/61b64406-b9eb-49b0-bffe-4a757da03fe9)

Price VRM

![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/e0a7bdc2-2f2f-41b5-8686-715e5b496529)
```

**Comment by pokeplayer2** [comment]
Argh, sorry and thx!

**Comment by pokeplayer2** [comment]
How fast is the chart re-created after config changes? It's very hard to check the configuration when the changes are not immediately visible ...

**Comment by dirkjanfaber** [comment]
Afaik historic graphs are not altered, so left of the vertical line keeps the calculations from that moment. The rest of the graph (right of the vertical "now" line) should be recalculated direct after changing the configuration. But I might be wrong on that, in which case it is max 1 hour.

**Comment by vbdaniel4** [comment]
Formula ist incorrect. Should be (in your case):
(p*1.19)+0.21
