### ISSUE TITLE
[VRM - Bug]: Grid feed from battery despite deactivation in setup

### ISSUE THREAD

**Issue by schwede70** [victronenergy/dynamic-ess#117]
### VRM portal ID

48e7dae08f17

### Country / region

Germany (de)

### B max

7

### TB max

3

### FB max

3

### TG max

30

### FG max

30

### Battery costs

0.05

### Buy price

(p+0.1178+0.0192)*1.19

### Sell price

fixed 0.082

### feed-in possible

yes

### feed-in control

yes

### What happened?

Monitored several phases of feed the grid from battery despite deactivation in setup of the dynamic ESS. 

![vrm-battery2grid_1](https://github.com/victronenergy/dynamic-ess/assets/121869737/4bc40725-ad2e-4e29-a988-e9b966f867ee)
![vrm-battery2grid_2](https://github.com/victronenergy/dynamic-ess/assets/121869737/593d623f-df5e-459b-b1da-2acc2f236b00)

### When did it happen?

09/11/2023 and days before

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by schwede70** [comment]
... additional information to the settings: feed from battery to grid is deactivated!
![vrm-battery2grid_3](https://github.com/victronenergy/dynamic-ess/assets/121869737/50599df1-bfa0-4b03-beef-b41d8c894f77)

**Comment by dirkjanfaber** [comment]
It looks like you are running v3.11, which does not support this functionality. The latest candidate versions however do. 

Updating can be done by setting the update feed to "candidate" and then updating the firmware.

**Comment by schwede70** [comment]
Yes, this assumption was correct! I was running on v3.11. Just updated to v3.20~18. I will try with this version and provide feedback!
Thanks!

**Comment by dirkjanfaber** [comment]
Thank you too. I'll close this issue then. We'll add an extra check to VRM that setting restrictions can only be done when running a capable version of Venus.
