### ISSUE TITLE
Sweden not selectable as a country.

### ISSUE THREAD

**Issue by MissMusic** [victronenergy/dynamic-ess#12]
Is there a reason why Sweden and Norway are missing in the country list?

**Comment by danjul89** [comment]
Would also like Sweden, im using FI for now.

**Comment by alvinpalv** [comment]
Waiting for the Swedish support! :)

**Comment by dirkjanfaber** [comment]
We are using the data from https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show to get the needed day ahead prices. For some reason Sweden and Norway are split up into regions. That is why we skipped them for now (most other countries don't have those). 
Can we assume that each one of you knows which reason is needed for your connection? In which case we can add them as selectable options to the list.

**Comment by danjul89** [comment]
> 

Alright, yeah most Swedes are based in SE3 and SE4(see picture below).
Im based in Sweden SE3 and @alvinpalv as well, you can perhaps create 4 "countries" named sweden i.e. **Sweden_SE[1-4]**

![image](https://github.com/victronenergy/dynamic-ess/assets/30293623/8cdd3c6e-a50e-4eb9-9ce2-eb421e2bdfe1)

**Comment by MissMusic** [comment]
>  Can we assume that each one of you knows which reason is needed for your connection? 

Yes, definitely. After the last few years with prices matching central Europe (quite a shock for us Swedes and Norwegians) everyone who didn't know what region they are in do now. If you make them as select-able country options it will be fine. If you want to be anal about it maybe rename the selection from country to energy region or something as that is what you are actually after.

**Comment by dirkjanfaber** [comment]
Support for the extra regions has been implemented in version 0.0.43, which is available from the palette manager.
