### ISSUE TITLE
[VRM - Bug]: Dynamic ESS error code: No matching schedule available

### ISSUE THREAD

**Issue by pokeplayer2** [victronenergy/dynamic-ess#121]
### VRM portal ID

c0619ab4ae0e

### Country / region

None

### B max

26

### TB max

6.5

### FB max

7

### TG max

30

### FG max

30

### Battery costs

0,02

### Buy price

(p+0.21)*1.19

### Sell price

0,115

### feed-in possible

yes

### feed-in control

no

### What happened?

Dynamic ESS error code: No matching schedule available: is a fresh error msg from today

### When did it happen?

21/11/2023 02:00

### Screenshots

![grafik](https://github.com/victronenergy/dynamic-ess/assets/21336708/cdf6d645-3ed3-4aa0-9fc1-9b5bfb0baf6f)

**Comment by pokeplayer2** [comment]
It would be good to have better filter function at the Alarm page.

**Comment by dirkjanfaber** [comment]
Closing this as duplicate from #120
