### ISSUE TITLE
[Feature]: Serve javascript from NR, not jsdelivr

### ISSUE THREAD

**Issue by AbelLykens** [victronenergy/dynamic-ess#124]
### Description

Hi! 

Currently Node Red /dess serves chart-js-javascript from an external source:
`<script src="[https://cdn.jsdelivr.net/npm/chart.js](view-source:https://cdn.jsdelivr.net/npm/chart.js)"></script>`
This means the page does not work in airgapped/not-internet-connected environments.

### Suggested Solution

Serve the chart.js file from the system itself, please.

**Comment by dirkjanfaber** [comment]
To me this seems to be a bit of an non-issue as it won't make sense to run the software without a internet connection anyway. The scheduling information is fetched hourly from the internet as well.

If you want to modify the location, you can adjust it in the function node called "html page".
