### ISSUE TITLE
FG max - exceeded

### ISSUE THREAD

**Issue by Cheeseyo** [victronenergy/dynamic-ess#126]
### VRM portal ID

c0619ab2fbc1

### Country / region

Germany (de)

### B max

20.25

### TB max

10.66

### FB max

10.66

### FG max

6.5

### Battery costs

0.05

### Buy price

(p+0.0798+0.0133+0.0159+0.0215)*1.19+0.0205

### feed-in possible

no

### feed-in control

None

### What happened?

Hi there,

I checked my installation today and the VRM portal dashboard showed that the import from the grid was over 11,000 W even though fg-max is set to 6.5 KW in the settings.

In the AC Input Power graphic you can see that all 3 phases have approx. 4000 W at the time of charging, as shown in the screenshot.

![Clipboard01](https://github.com/victronenergy/dynamic-ess/assets/91350179/d6046b35-3621-440e-825d-11b75b414c7a)

Could it be because the fg-max with decimal places doesn't work properly? Or does the value in the settings apply to a single phase and I would have to set the value to 2.15 KW.

### When did it happen?

11/01/2024 10:00 to 14:00

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
See https://www.victronenergy.com/live/drafts:dynamic_ess#qwhy_does_the_system_exceed_the_configured_power:

> Q: Why does the system exceed the configured power?
> 
> During the configuration of the system, you are setting the capacity of the system, not the actual limits of the system. These capacities are used by the system to make its calculations, so it used as an average power the system can do in an hour.
If you want to limit the feed-in power to the system, you can do that. This is done via the ESS → Grid feed-in menu on the console. The system will not exceed this limit.
> 
> On the other side of limiting power (what gets pulled from the grid) is more tricky. If you have all of your loads behind the Victron system, you can use the AC input current limit. If you don't have all of your loads behind the Victron system, there is currently no configurable option to limit the total input of all of your loads. Especially when you have high loads (EV charger, heat pumps) before your Victron system, there is a chance of blowing your main fuse. We are working on a way to account for the loads that will limit the power the system can take. But at the moment that is not available yet.
