### ISSUE TITLE
BUG: Dynamic ESS not in Node-RED mode (undefined)

### ISSUE THREAD

**Issue by AbelLykens** [victronenergy/dynamic-ess#128]
### What happened?

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/5dcda7e2-b700-4352-bffa-1238d6c1ac4c)

I installed/imported the new flow. But it does not want to start.

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/abf70ac5-6004-4b66-8b34-1b2f7a15cb25)

The inject did not work:

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/7cd4ec37-4840-4e93-981e-e53b319787da)

### When did it happen?

2024-02-27 13:41 cet

### Versions
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/d9dbb3f7-1d58-4ae0-8578-fe717027b729)
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/17ad2b1e-fae4-4a18-a7fd-106a2fe3ae5e)

**Comment by dirkjanfaber** [comment]
And does manually clicking on that box next to "Enable Dynamic ESS (mode: Node_RED)" help?

**Comment by AbelLykens** [comment]
No luck:
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/2f201e2b-7ad7-43dd-8c45-14514e366987)

**Comment by dirkjanfaber** [comment]
Not sure how I can reproduce this. What is your VRM or site id?

**Comment by AbelLykens** [comment]
I'm `c0619ab4b555` :)

**Comment by AbelLykens** [comment]
Now reverting to old firmware. Let's see if I get dess back.

**Comment by AbelLykens** [comment]
Now on v3.22, no luck. It all seems kinda broken now (no dynamic things going on) . Not sure what steps to take.

**Comment by dirkjanfaber** [comment]
I got it fixed on your site. For some reason the Victron Energy Client configuration node was not there. Added that one to your Node-RED installation. 

Now for me to figure out how that happened and prevent it from happening again.

**Comment by dirkjanfaber** [comment]
Closing this issue. If it happens again, I'll investigate deeper.

**Comment by Tomashaglund1** [comment]
> Victron Energy Client configuration

Hi, what node is "Victron Energy Client configuration node"? Most probably I'm having the same problem... Unable to activate dynamic ESSmode 4, it results in the error code on the right hand side in below screenshot.

![image](https://github.com/victronenergy/dynamic-ess/assets/146727423/07204aa1-74dc-4848-8cdc-7baa5f7ea096)

**Comment by dirkjanfaber** [comment]
Easiest solution is to drag another Victron node into the canvas, press deploy once and then it should appear.

**Comment by Tomashaglund1** [comment]
Tried adding grid meter however it's stating "Unable to access the service endpoint."

![image](https://github.com/victronenergy/dynamic-ess/assets/146727423/c7376592-90f0-457b-9faf-ebd64859a7cd)

**Comment by Tomashaglund1** [comment]
Thanks got it working! :)
