### ISSUE TITLE
[Bug]: AxiosError: Request failed with status code 408

### ISSUE THREAD

**Issue by GizmoQ2k** [victronenergy/dynamic-ess#129]
### Contact Details

martin@sieradzki.org

### VRM portal ID

c0619ab33f21

### Country / region

Germany (de)

### B max

10

### TB max

5

### FB max

3.2

### TG max

0

### FG max

2.5

### Battery costs

0.025

### Buy price

(p+0.139)*1.19

### Sell price

(p+0.139)*1.19

### feed-in possible

no

### feed-in control

yes

### Version

0.1.14

### What happened?

I'm always getting "AxiosError: Request failed with status code 408" and Dynamic ESS tells me "Could not create a feasible schedule". It was working, i just changed some parameters and deployed again, it stopped. Reverting the changes does not help, restart does not help, even reimporting the flow does not help.

### When did it happen?

28/02/2023 12:00

### Relevant log output

```shell
29.2.2024, 10:40:24node: Dynamic ESS
msg : Object
{ url: "https://vrm-dynamic-ess-api.vi…", options: object, headers: object }
29.2.2024, 10:40:27node: Dynamic ESS
msg : error
"AxiosError: Request failed with status code 408"
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
A http 408 code means that the connection timed out. The only thing I can think of that might cause this is if your DNS is unable to resolve `vrm-dynamic-ess-api.victronenergy.com` or that your firewall does not allow the https connection to that host.
