### ISSUE TITLE
[Bug]: Noooo don't take from battery when prices are very low... ;)

### ISSUE THREAD

**Issue by AbelLykens** [victronenergy/dynamic-ess#130]
### Versions
v3.30~7
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/d5041696-2e1c-4101-8b1c-3761c8759f27)

### What happened?

Very odd/unexpected. Prices currently are very low. So I started my washing machine and dishwasher.

But it seems to take power from the battery. That does not make a lot of sense, does it?

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/1a2b243c-39d6-4a29-9830-3d9fde490d39)

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/cf6c1506-298a-4c83-91b0-d55313731d09)

### When did it happen?

20240305T1301 CET

**Comment by dirkjanfaber** [comment]
Just make sure. You are using the latest flow? The one that also sets restrictions and strategies?

**Comment by AbelLykens** [comment]
Yes pretty sure :) Upgraded a week ago or so :)

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/e5b4f906-03e5-4a24-9cf7-21b85e657794)

**Comment by AbelLykens** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/d1973094-b242-44eb-802c-5f5ec0ab5403)

It's currently delivering energy back, and next hour it plans to take from the net... Not ideal.


![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/2412968b-7a06-4b9f-859f-4e2ff7dd826d)

**Comment by dirkjanfaber** [comment]
We did have some updates on this from 3.30~13 (which you are running right now) to 3.30~17 (latest right now). Can you update and check if the problem persits?

**Comment by AbelLykens** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/ce95066c-11c1-4bae-a33e-b67b6eb66bcb)
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/e1f93bc3-e89f-469c-95a7-066b1e02a373)
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/12ae3e8c-de4c-4090-85c1-6af61220c481)
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/62f0a631-d43c-4d6e-831a-2c4a90c6aa67)

System is now getting in more solar than expected. Prices will rise in a bit, and the battery is not full. Would be nice if it charged rather than fed back 👀

**Comment by dirkjanfaber** [comment]
Did you notice the new releases option to add extra (most of the time solar) energy into the battery to reduce the grid usage during the first part of the night. 

<img width="465" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/c3a4570a-815d-4865-9d10-6344b5bb2765">

**Comment by AbelLykens** [comment]
I must admit the `b_goal` does not (yet?) make much sense to me. Have not used it yet. But will set it to 50%/0 (as per your screenshots) and see what it does 😄

**Comment by AbelLykens** [comment]
Right I see. I think that makes sense. Let's set it and see what happens. Would be useful if `goal_hour` would dynamically change based on expected sun I suppose. But this is cool already. Let's see what happens.

**Comment by AbelLykens** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/98dedf18-037f-418f-aa18-9c5fa707f4a0)
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/12d9cdcb-914b-40fb-8a44-22207cc63c9f)
I updated to 0.1.17. And I set the variables. No luck yet, it seems. I kinda expect the blue line to go to at least 80% at 20:00?

Will now update the cerbo to `v3.30~21` and report back.

**Comment by dirkjanfaber** [comment]
That is what I would have expected too. It should already work with the previous firmware.

**Comment by AbelLykens** [comment]
No luck for me yet on `v3.30~21` with `0.1.17`.

![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/aaae9c8e-0d30-4db8-9352-82c09f7a75c0)
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/14fd0fe5-1dca-4f51-8fa4-a125464cd037)

**Comment by AbelLykens** [comment]
Something happened! It's getting energy now. Cheers.

**Comment by dirkjanfaber** [comment]
I'll close this issue now as it seems to be resolved.
