### ISSUE TITLE
[Bug]: /dess stopped working after update to v0.1.15

### ISSUE THREAD

**Issue by AbelLykens** [victronenergy/dynamic-ess#132]
### What happened?

I upgraded to v0.1.15 (palette manager --> click upgrade --> wait for upgrade to finish --> disable Node Red --> enable node red).
I then entered 0 and 0 for the b_goal vars.
Deployed and restarted flows. But now I am getting HTTP/504 on /dess.

Should I do something differently?

**EDIT:**
I also now imported a copy of the flow, deleted the old flow. Interestingly, I had to set the b_goal vars again. And I restarted the whole cerbo. No cigar.

### When did it happen?

2021-03-15 16:55

### Relevant log output

```shell
Not sure where to get logs.
```

**Comment by AbelLykens** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/47113175/9d78e832-ed32-4847-9add-e8c03c0d09c9)

Tried reinstalling and restarting. No luck. I am `c0619ab4b555` if you can take a look.

Also I see https://vrm-dynamic-ess-api.victronenergy.com/ returns HTTP/500, not sure if that is related.

**Comment by AbelLykens** [comment]
Solved the "Not in ESS Mode" by following your previous hint:
https://github.com/victronenergy/dynamic-ess/issues/128#issuecomment-1977283049

still no /dess though ;)

**Comment by dirkjanfaber** [comment]
What is your vrm id? I'll probably take a look at it later today.

**Comment by AbelLykens** [comment]
Whoo magically /dess returned!

**Comment by dirkjanfaber** [comment]
I fixed it on your site. Will push a new update out after dinner.

**Comment by AbelLykens** [comment]
Eet smakelijk and thanks!

**Comment by dirkjanfaber** [comment]
Thanks Got 0.1.16 out. For you there is not much need to update. Though it can't hurt.

**Comment by Tomashaglund1** [comment]
Similiar problem here venus.local:1881/dess is not working after update from V0.1.14 --> 0.1.17 page renders --> "Node-RED unreachable". Dynamic ESS seems to be working tough.
Getting the error "Could not create a feasible schedule" after the 0.1.15 update most likely.
Ideas?

![image](https://github.com/victronenergy/dynamic-ess/assets/146727423/5d48ad63-0489-4509-b940-9a78ec3fcde3)
