### ISSUE TITLE
[VRM - Bug]: DESS Minimum SOC resets to ESS Minimum SOC 

### ISSUE THREAD

**Issue by gu5n** [victronenergy/dynamic-ess#137]
### Contact Details

christoph.abloescher@gmail.com

### VRM portal ID

c0619ab1d9df

### Country / region

Austria (at)

### B max

14.4

### TB max

9

### FB max

9

### TG max

17

### FG max

11

### Battery costs

0.02

### Buy price

(p+abs((p*0.03))+0.015)*1.2

### Sell price

0.04

### feed-in possible

yes

### feed-in control

None

### What happened?

The DESS Minimum SOC resets after a few minutes back to the ESS Minimum SOC and is never applied/used.

Screenshot after changing the value from 10% to 25%:

![Screenshot_20240414-120514](https://github.com/victronenergy/dynamic-ess/assets/26893205/6d6aacd8-032f-4b2a-8fe4-5ff51ce05303)

After a few minutes and/or a change in the DESS config (eg battery capacity), the value changes back to 10% without notification. VRM also never shows the 25% value in the forecast.

Screenshot after reset:
![Screenshot_20240417-205505](https://github.com/victronenergy/dynamic-ess/assets/26893205/2732fcf0-cfa9-4043-b818-2d67d3c91107)

I can't use DESS like that as my forecasted consumption at night ist always off.

### When did it happen?

17/04/2024 20:54

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
This is a remnant of an older implementation that should have been removed from the menu a while ago. But we forgot about it. And it adds confusion. Sorry about that. This menu option will be out in the next release.

You need to adjust the regular _Minimum SOC (unless grid fails)_, which is also used by DESS (and one menu up). You can also check the current value on VRM under the controls.
