### ISSUE TITLE
[Bug]: Unable to alter Green mode on setting .

### ISSUE THREAD

**Issue by MichaKersloot** [victronenergy/dynamic-ess#138]
### Country / region

None

### feed-in possible

None

### feed-in control

None

### What happened?

I've unchecked the Green Mode, Deployed, but the system keeps charging as if the green_mode_on setting was still on. Looking in the Context Data green_mode_on still is true there:

![image](https://github.com/victronenergy/dynamic-ess/assets/3512195/206a6741-e5c4-498a-9f8f-dcd89828e94e)

### When did it happen?

23-04-2024 11:00

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
Yes, noticed it this morning too and working on an update. Probably to be released this afternoon.

Keeping this issue open until it has been released.

**Comment by dirkjanfaber** [comment]
Yes, I'll add that.

**Comment by MichaKersloot** [comment]
The setting seems to 'stick' now! But it looks like the calculations are still based on green_mode_on = true despite it setting to false. (id: c0619ab410ae )
