### ISSUE TITLE
United Kingdom not available

### ISSUE THREAD

**Issue by apple047** [victronenergy/dynamic-ess#14]
Hi, just came across dynamic-ess but UK is not available, would you consider supporting please?

Thanks

**Comment by dirkjanfaber** [comment]
This will be solved via issue #12

**Comment by dirkjanfaber** [comment]
I am sorry about that, but it appears that dynamic pricing for the UK is not provided by Entsoe right now. 

<img width="811" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/4d5ca2cb-f29a-4588-9769-18c4105f07db">

I will need to close the issue again as there is no way to add the UK without this information. Perhaps there is an alternative API available for the UK and we are just not aware of that. If you find one, please let us know and we'll add it.
