### ISSUE TITLE
[VRM - Bug]: dynamic ess menu not visible anymore

### ISSUE THREAD

**Issue by Wim275** [victronenergy/dynamic-ess#147]
### Contact Details

wim@clinckspoor.be

### VRM portal ID

c0619ab4a1a9

### Country / region

Belgium (be)

### B max

8

### TB max

4

### FB max

4

### TG max

15

### FG max

22

### Battery costs

2.7

### feed-in possible

None

### feed-in control

None

### What happened?

A bug happened!
For some reason, the ess setting menu disappeared in the navigation of the vrm. In the dashboard I can still swith ess on and off.

### When did it happen?

Don’t realy know

**Comment by schlotze** [comment]
I have the same problem.
I am running venus os v3.40

**Comment by Wim275** [comment]
I have 3.13, but nobody from victron seems to pick up this problem, are there other ways to contact victron support ?
Wim.

**Comment by mpvader** [comment]
Hey both, I’ll make sure someone looks into this tomorrow / check what is being done on this.

**Comment by mpvader** [comment]
> A bug happened!
> For some reason, the ess setting menu > disappeared in the navigation of the vrm. In the > dashboard I can still swith ess on and off.

You mean the dynamic ess menu in VRM, right?

> I have 3.13

Venus OS v3.13 is quite old; for any trouble shooting; first thing to do will be to update it to the latest version; which at the moment is Venus OS v3.40

**Comment by Wim275** [comment]
Thanks for your answer, yes the dynamic ess menu is not there anymore. 
![5DB25E91-9303-46C5-A231-24023B9B39B3](https://github.com/user-attachments/assets/d5d18012-4e82-41b1-b570-e16f1215ef32)
![B9375653-3AC7-4BE5-8A4F-EE4EBB726205](https://github.com/user-attachments/assets/c50841e2-dc05-4f61-b3bc-c02f38e5b775)

**Comment by Wim275** [comment]
I’m on holliday now, I will do the os firmware upgrade on the 3th of august.
