### ISSUE TITLE
مسار تمت مشاركته

### ISSUE THREAD

**Issue by Mmohmd** [victronenergy/dynamic-ess#167]
مسار تمت مشاركته
من (24.7060790,46.6591213) إلى مركز ثيله الصحي، G4F4+9X، ثيله، اليمن عبر المسار 177.

١٨ س ٥٧ د (١٬٤٥٣‏ كم)
١٨ س ٥٧ د بالنسبة إلى حركة المرور الحالية
تجنّب الطرق السريعة, تجنّب رسوم العبور, تجنّب العبّارات

1. الاتجاه نحو  شمال غرب مباشرة صوب طريق العروبة الفرعي
2. الاتجاه يمينًا إلى طريق الملك فهد الفرعي
3. الاتجاه نحو الطريق المنحدرة إلى اليسار إلى طريق الملك فهد
4. الدخول في طريق الملك فهد
5. إلى اليسار قليلاً إلى ‪Al Hameid‬‏/المسار 65
6. الاتجاه نحو المخرج إلى الطريق الدائري الجنوبي الفرعي
7. الدخول في البطحاء/طريق الحائر
8. الاتجاه نحو  اليسار إلى شارع رقم 2
9. الاتجاه نحو  اليمين
10. عند الدوّار، عليك الاتجاه نحو المخرج الأول 
11. الخروج من الدوار
12. عند الدوّار، عليك الاتجاه نحو المخرج الثالث 
13. الخروج من الدوار
14. الاتجاه نحو  اليمين قليلاً
15. الاتجاه نحو الطريق المنحدرة إلى طريق الحاير حوطة بني تميم
16. الاتجاه نحو الطريق المنحدرة إلى طريق الملك فهد
17. عند الدوّار، عليك الاتجاه نحو المخرج الثاني  والاستمرار في طريق الملك فهد
18. الخروج من الدوار باتجاه طريق الملك فهد
19. عند الدوّار، عليك الاتجاه نحو المخرج الثاني  والاستمرار في طريق الملك فهد
20. الخروج من الدوار باتجاه طريق الملك فهد
21. عند الدوّار، عليك الاتجاه نحو المخرج الثاني  والاستمرار في طريق الملك فهد
22. الخروج من الدوار باتجاه طريق الملك فهد
23. عند الدوّار، عليك الاتجاه نحو المخرج الثاني  والاستمرار في طريق الملك فهد
24. الخروج من الدوار باتجاه طريق الملك فهد
25. عند الدوّار، عليك الاتجاه نحو المخرج الثاني  والاستمرار في المسار 10/المسار 90M
26. الخروج من الدوار باتجاه المسار 10/المسار 90M
27. تابع جهة‏ ‏اليسار‏‏ واستمر في القيادة على الطريق‏ المسار 10/المسار 90M
28. عند الدوّار، عليك الاتجاه نحو المخرج الأول  إلى ‪Leila - Al Soulayyil‬‏/المسار 10/المسار 90M
29. الخروج من الدوار باتجاه ‪Leila - Al Soulayyil‬‏/المسار 10/المسار 90M
30. المتابعة مباشرة في ‪Khamis - Al Soulayyil‬‏/المسار 10/المسار 90M
31. الاتجاه يسارًا إلى المسار 177
32. الاتجاه نحو اليسار
33. المتابعة في خط مستقيم
34. تابع جهة اليسار
35. المتابعة في خط مستقيم
36. الاتجاه يمينًا إلى المسار 15
37. الاتجاه يسارًا إلى المسار 1050
38. المتابعة مباشرة في ‪556‬‏/‪P 556‬‏
39. المتابعة في خط مستقيم
40. الاتجاه نحو اليسار
41. الاتجاه نحو اليسار
42. الاتجاه نحو  اليمين
43. المتابعة في خط مستقيم
44. عند دوار جولة آية، عليك الاتجاه نحو المخرج  الثالث   باتجاه شارع النصر
45. الخروج من الدوار باتجاه شارع النصر
46. إلى اليسار قليلاً إلى جسر الشهيد حميد الملصي
47. الاتجاه نحو  اليسار قليلاً
48. الدخول في ‪Nashwan Al-Himyarist‬‏/‪Ring Rd‬‏
49. تابع جهة اليسار
50. عند الدوار، تابع السير مباشرةً في شارع خولان
51. عند الدوّار، عليك الاتجاه نحو المخرج الأول 
52. الخروج من الدوار
53. الاتجاه يسارًا إلى شارع تعز/طريق صنعاء - تعز
54. الاتجاه نحو  اليمين
55. الاتجاه نحو اليسار
56. الاتجاه نحو اليسار
57. الاتجاه نحو اليسار
58. الاتجاه نحو المخرج إلى طريق صنعاء - تعز
59. الاتجاه نحو  اليمين
60. الاتجاه نحو اليمين إلى خط الحسينيه
61. الاتجاه نحو  اليمين
62. الاتجاه نحو اليسار
63. الاتجاه نحو  اليمين
64. تابع جهة اليمين
65. الوصول إلى الموقع: مركز ثيله الصحي
للوصول إلى أفضل مسارٍ نظرًا لحركة المرور الحالية، يُرجى زيارة https://maps.app.goo.gl/ze7RUwVzSXCv2aDs6

**Comment by dirkjanfaber** [comment]
Please use English if you want support.
