### ISSUE TITLE
Possibility to add ESS name to dashboard?

### ISSUE THREAD

**Issue by banne123** [victronenergy/dynamic-ess#19]
Would it be possible to add the dynamic ESS name on the dashboard? I have three Victrons to monitor, now need check URL everytime to see if i'm looking at the right one...

**Comment by dirkjanfaber** [comment]
You can add a "text" node to the flow, containing the system name, taken from the settings node. Something like this:

```
[{"id":"4419fb273e979980","type":"ui_text","z":"3cedf502010030d2","group":"ae94fc0e9881e8c0","order":3,"width":0,"height":0,"name":"","label":"System name","format":"{{msg.payload}}","layout":"row-spread","className":"","style":false,"font":"","fontSize":16,"color":"#000000","x":560,"y":640,"wires":[]},{"id":"0a513886f21b4c74","type":"victron-input-settings","z":"3cedf502010030d2","service":"com.victronenergy.settings","path":"/Settings/SystemSetup/SystemName","serviceObj":{"service":"com.victronenergy.settings","name":"Venus settings"},"pathObj":{"path":"/Settings/SystemSetup/SystemName","type":"string","name":"System name"},"name":"","onlyChanges":false,"x":240,"y":640,"wires":[["4419fb273e979980"]]},{"id":"ae94fc0e9881e8c0","type":"ui_group","name":"Visualisations","tab":"cc1a49b54f71c790","order":2,"disp":true,"width":"24","collapse":false,"className":""},{"id":"cc1a49b54f71c790","type":"ui_tab","name":"Dynamic ESS","icon":"dashboard","order":1,"disabled":false,"hidden":false}]
```
![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/f1a274ba-a3cd-4574-af72-c8cf5c69626d)

In the future this implementation in Node-RED will become obsolete as the functionality will move into VRM/Venus OS native. We are focusing our efforts on getting that done and limiting the Node-RED development right now to fixing bugs.
