### ISSUE TITLE
PV yield flat line

### ISSUE THREAD

**Issue by banne123** [victronenergy/dynamic-ess#20]
Hope nobody thinks I'm annoying :-) , new to Node Red and automating the ESS...

On what is the PV yield based? There is no explaination in the "about". I have AC coupled inverters (which are also enabled in the Console) but my PV line in the dashboard is still flat... Is that only enabled and working for DC coupled PV? From what I tried to understand about it is that the algo will keep in mind that the batteries can be charged with excessive solarpower. I have a gridmeter connected to my Victrons to monitor the feed in to the grid

**Comment by dirkjanfaber** [comment]
The system is designed around DC coupled PV (solar power). As mentioned [here](https://github.com/victronenergy/dynamic-ess#prerequisites), (wind)generators are not supported right now.

**Comment by MichaKersloot** [comment]
Am I correct the algorithm takes the real numbers from VRM in account? There is no upload via node-red as far as I'm aware of. In that case, of you manage to register your AC coupled PV as a PV Charger in the VRM there shouldn't be an issue in using that in the DynESS algorithm? I have no experience with this at all as I'm using an Easysolar II GX, but I did see several options in the software to include an AC coupled PV.
