### ISSUE TITLE
[Bug]: Active SOC value not working for mode with BatteryLife

### ISSUE THREAD

**Issue by khostri** [victronenergy/dynamic-ess#25]
### Contact Details

jan.slaby@outlook.com

### VRM / Site iD

210204

### Country / region

Czech Republic (cz)

### B max

20

### TB max

8.5

### FB max

8.5

### TG max

9.9

### FG max

12

### Battery costs

0.07

### Buy price

(p+0.150675)*1.21

### Sell price

(p-0.0276)*1.21

### feed-in possible

- [X] yes
- [ ] no

### feed-in possible

- [X] yes
- [ ] no

### What happened?

Minimum  OC is correctly displayed in NodeRED flow (currently 45%) but algo prediction and visualisation on DAshboard still counts with basic value and thinks it can go as low as 15% today

### Screenshots

![image](https://github.com/victronenergy/dynamic-ess/assets/10581890/656d6d0f-529f-4723-8154-c22c095203c0)
![image](https://github.com/victronenergy/dynamic-ess/assets/10581890/198459b1-e068-41e5-9c75-6cb261c31055)

**Comment by dirkjanfaber** [comment]
The latest version of dynamic ESS now uses the target SOC instead of the setpoint. Making this issue no longer relevant.
