### ISSUE TITLE
 [Feature]: Throttling the charging and discharging when the price window is large enough to maximise system efficiency

### ISSUE THREAD

**Issue by MarcoFace** [victronenergy/dynamic-ess#30]
### Contact Details

marcofaasse@protonmail.com

### Description

The algorithm goes full blast while charging and discharging regardless of the parameters set in the dynamic-ess node. 
In some cases this may be fine but often the price windows to charge at low rates or sell at high rates are wider than the maximum charge and discharge times of my system. As a result the system efficiency is lower that necessary. 
A full blast cycle drops my system efficiency from an average standard ESS score of 88.5% to only 77%.

### Suggested Solution

Suggested solution is to make the price window time determine the charge and discharge currents to optimize efficiency.

**Comment by dirkjanfaber** [comment]
In the next update, the steering mechanism will change and be based on reaching a target Soc instead.  And it will try to do that gently within the hour.
