### ISSUE TITLE
[Feature]: Battery temperature ceiling parameter for longevity batteries when price arbitraging large energies

### ISSUE THREAD

**Issue by MarcoFace** [victronenergy/dynamic-ess#37]
### Contact Details

marcofaasse@protonmail.com

### Description

When the algorithm decides to charge the batteries it does so at the power settings set under ESS and DVCC
For some systems this may result in rather high battery temperatures being reached.
If not on the charging session then possibly on the discharge session thereafter.
Especially in seasonal countries it is not practical to manually adjust the ESS and DVCC power limits 

### Suggested Solution

In the event this is desirable (It is not always as per issue #30) it would be useful to allow the algorithm to throttle charging based on a maximum battery temperature parameter. Let's say 35 degrees Celsius. If charging started at 24 degrees Celsius and half way the battery temperatures are up to 30 degrees it would make sense for the algorithm tot throttle the charging power to not exceed 35 degrees Celsius.

Furthermore in the event the algorithm economically would like to price arbitrage a lot of energy in a short time window (charge + discharge) this may not be technically feasible without exceeding safe temperatures. As such it would be useful if the algorithm could learn the site battery units temperature dynamics and take them into account when deciding how much to price arbitrage in a certain time window to stay within temperature limits.

Even for and airconditioned setup it would be a good safety feature in case the AC broke down.

### Additional Context

Managing the price arbitrage energy flows based on safe battery temperature avoids excessive wear of equipment and allows for more system effectiveness than the current manual settings as manually one would need to leave more safety margin and thus forego arbitrage volume / grid stability contribution.

**Comment by mpvader** [comment]
Hi, thats a nice idea. We'll look at that further down in the future. Its not a priority for us now.
