### ISSUE TITLE
[Feature]:  Consideration for car charging/diverting to hot water tank

### ISSUE THREAD

**Issue by ajaxharg** [victronenergy/dynamic-ess#38]
### Contact Details

ajaxharg@gmail.com

### Description

I am running my own dynamic ess solution that is highly tailored to my setup.  There are a few things that might adversely affect the prediction based on historic usage.  People will often charge their cars in the cheap period/sunny times in the summer.  If this is fed into the historic data then the dynamic part of it will start to make incorrect decisions holding back battery and then not having any space to charge from solar.  Other things that can also be high power but a bit random include diverting spare solar to hot water tanks and heat pumps.

I have a house hold base load graph that I work against and then display daily spare solar and battery SOC for the day ahead to let me decide if I charge the car or not.  It is very difficult to automate as so many factors need to be considered. Car charge required, inefficiencies at low charge rate vs higher charge rate.

### Suggested Solution

Is there some way of filtering consistent high power loads from the base load graph?  At least then the future predictions are just the normal household use and the user can decide if they want to plug in the car or not?  Its not terribly important for me as I'll continue to use my solution not least since I can't feed the prices in but its something that probably needs to be considered.

**Comment by mpvader** [comment]
Hi, thanks, eventually we'll for sure look at those things. But not yet. I'll close this issue to keep the tracker workable.
