### ISSUE TITLE
Other countries not working

### ISSUE THREAD

**Issue by DarkFiguringitout** [victronenergy/dynamic-ess#4]
I setup the program as described, and filled out my data using germany as the country. However I was met with error, Error 500 Internal Server Error.

After multiple tries, I changed the country to netherlands, and it worked perfectly! As soon as I changed it to germany again, it did not work anymore. Does anyone have a fix for this please? 

I find this project quite facinating. My current flow is very stupid, but it works. This project is so much better if it works!

**Comment by dirkjanfaber** [comment]
We are working on supporting more countries. See also issue #2.

Closing this issue not to have duplicate ones.
