### ISSUE TITLE
[help]: 

### ISSUE THREAD

**Issue by Tom-Moser** [victronenergy/dynamic-ess#40]
### Contact Details

darktom@gmx.at

### VRM / Site iD

48e7da85adab

### Country / region

Austria (at)

### B max

14

### TB max

6

### FB max

7

### TG max

0

### FG max

3.6

### Battery costs

0.04

### Buy price

(p+0.02+0.13)*1.21

### feed-in possible

no

### feed-in possible

yes

### What happened?

Guten Tag 

Hab den Flow wie in der Anleitung installiert.  VRM Token erstellt, Tolle Anleitung übrigens.
nur der Baustein "VRM Dynamic ESS" hat ein rotes Quadrat [ object Object ] ich finde keinen Lösung ?
![debug_ESS](https://github.com/victronenergy/dynamic-ess/assets/140938977/c9d8b907-7865-4d87-a819-d296382eb91b)
![DY_ESS_set](https://github.com/victronenergy/dynamic-ess/assets/140938977/d481a088-2e52-4cd7-bd3b-1308e146b927)

ich verwende keine Victron Batterie, kann das die Ursache sein ?  
![Dy_ESS_flow ](https://github.com/victronenergy/dynamic-ess/assets/140938977/87a5c7b4-a957-4890-af5d-2e78718fb4f9)

ich hab alle meine flow´s deaktiviert um sicher zu gehen das die nicht stören. 
![flows_deaktiviert](https://github.com/victronenergy/dynamic-ess/assets/140938977/e76d410f-c3a1-4439-b4fa-02e2601833b8)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
Thanks for the report. This should not happen. Are you still seeing this problem?

**Comment by Tom-Moser** [comment]
Guten tag 
Hat sich nichts verändert. 
Eventuel liegt es an meiner Firewall. Wo kann ich sehen welche ports der baustein (node)  braucht, beziehungsweise auf welche seiten er zugreift?

**Comment by dirkjanfaber** [comment]
The node does make a call to https://vrm-dynamic-ess-api.victronenergy.com. I'll try to replicate your issue next week to at least make the error more clear. Is there any more info in the debug tab that might help debugging this?

**Comment by dirkjanfaber** [comment]
Sorry for the late response, but it looks like you are using the vrm_id (`48....`)  instead of the site id in the query. Yours is `14...`.
