### ISSUE TITLE
Why doesn’t Victron obey nodered schedule 

### ISSUE THREAD

**Issue by Mableeker** [victronenergy/dynamic-ess#43]
I’ve installed Venus os large, node red, dynamic ESS. Charging according to schedule goes well, but discharge not. It sets to pv only not pv & battery. Again… why is this only with me when everyone is fine? Struggling with it for 3 months now ..
![IMG_3977](https://github.com/victronenergy/dynamic-ess/assets/118760571/74b5f1ff-ec59-4d5d-801a-800ebc6acb73)
![IMG_3979](https://github.com/victronenergy/dynamic-ess/assets/118760571/8b2facb8-92fe-42dd-94a0-e0e9a66dd3f3)
![IMG_3980](https://github.com/victronenergy/dynamic-ess/assets/118760571/6d6a6382-163c-496c-a060-2914f5ec8ae0)
![IMG_3981](https://github.com/victronenergy/dynamic-ess/assets/118760571/ebe191fc-93a3-45c9-ac8c-73da6b1fa7c1)
![IMG_3978](https://github.com/victronenergy/dynamic-ess/assets/118760571/d9954829-5f2e-4d47-b010-906acaf481e2)

**Comment by Mableeker** [comment]
Disabled again unfortunately still not working here...

**Comment by Mableeker** [comment]
Scheduled charging goes well, discharging not

**Comment by MichaKersloot** [comment]
Hi,

Your screenshot shows the battery is set to idle, so that's the reason for the settings in the GX device.  The reason why, is something the portal decides. But costs and minimum battery usage is taken in consideration.

**Comment by Mableeker** [comment]
At this moment 21.20 hrs, it should be discharging, but unfortunately no action.

**Comment by Mableeker** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/45aa7702-c782-4137-a718-f63e8070dc45)

**Comment by Mableeker** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/cbd539a8-20bf-4a0b-a7e0-207cbc4696f4)

**Comment by MichaKersloot** [comment]
And what were the ESS settings at that time? There shouldn't be an active schedule in de ESS settings and the setpoint should be at -3000 as far as i'm aware.

**Comment by Mableeker** [comment]
I'll check again this evening, the settings were as shown in the posted screenshots. So an active schedule.

**Comment by Mableeker** [comment]
Right now it should be discharging, but nothing happens, it has an active schedule ![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/b5d748bb-f80a-40a0-8879-dcc4b4db083d)![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/5a7e877b-f330-4069-a7e2-3e004a2b0678)

**Comment by MichaKersloot** [comment]
Hi,

i'm sorry, but there is just one more or less important piece missing in your screenshots. And that's the bottom line which shows the actual status of the system. I'm interested if the battery is set to idle when there is an active schedule. This way we can check if the node-red controls and the GX device are in sync.

If that is the case, the next thing would be to find out why the graphs and the controls are out of sync.

**Comment by Mableeker** [comment]
This one?
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/91dc3d18-276f-46c2-884d-13e9d83d9f58)

**Comment by MichaKersloot** [comment]
Yes, and the check there is no active schedule at 21:xx in the GX device. The screenshots above are from 20:xx

**Comment by MichaKersloot** [comment]
Hmm.. not sure if it matters, but looking at your screenshots you've set mode to: 'optimized (with batterylife)'. Because of my LiFepo4 batteries I've chosen for 'optimized (without batterylife)'.

**Comment by Mableeker** [comment]
I'll change that and see what happens today 👍. I have pylontech us5000 connected.

**Comment by Mableeker** [comment]
It's discharging 👍
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/d7e8a57a-3138-42ae-aa01-d1fdf8102766)
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/e3761c74-a083-4a6a-93fe-1514b947c0e8)
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/9178f1be-d2f4-4b11-baaa-1c315c2a061d)

**Comment by Mableeker** [comment]
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/055b454e-2a1f-491c-9a88-aa296114f52e)

**Comment by Mableeker** [comment]
It's working for 3 days now, according to charge/discharge schedule. The setting 'optimized with/without battery life' seems to make te difference. Thanks for the help Micha!
