### ISSUE TITLE
[Feature]: Dynamic input variables

### ISSUE THREAD

**Issue by Gr1pen** [victronenergy/dynamic-ess#44]
### Contact Details

tonny@gripagarden.se

### Description

As it is now the parameters for To Grid, From Grid, To Battery, From Battery etc is configured as static values in the configuration of the node. If these values could be configured by sending messages to the input of the node, it would be really easy to adjust to different installations and needs and also easy solve some of the other feature requests.

Look at the "Power Saver" node and the "dynamic config":
https://powersaver.no/nodes/ps-strategy-lowest-price.html#description
### 

### Suggested Solution

Make the node accept incoming messages to control the node's config parameters dynamically.

**Comment by dirkjanfaber** [comment]
It already does that. You can set different `msg` fields, e.g. inject a `msg.tb_max`. 

![image](https://github.com/victronenergy/dynamic-ess/assets/3098947/52e97934-c72a-47ee-9463-45fc73fb1572)

**Comment by Gr1pen** [comment]
That is just fantastic! :)  
Sorry I missed that in the documentation.
