### ISSUE TITLE
[Bug]: DynESS graph with error in positive negative axis

### ISSUE THREAD

**Issue by SimonYoungtree** [victronenergy/dynamic-ess#46]
### Contact Details

siempoot@gmail.com

### VRM / Site iD

287956

### Country / region

Netherlands (nl)

### B max

not relevant

### TB max

not relevant

### FB max

not relevant

### TG max

not relevant

### FG max

not relevant

### Battery costs

not relevant

### Buy price

not relevant

### Sell price

not relevant

### feed-in possible

None

### feed-in possible

None

### What happened?

One graph on the NodeRed Dashboard has switched positive negative display, or explanatory text is wrong.

Text says "positive values represent the energy pushed to the item". In the example you can see that on 2pm the battery is being charged (due to low prices), however this is represented as a negative value in the graph. This is contradicting the explanatory text.

### Screenshots

![DynESS - Screenshot 2023-09-04 091450](https://github.com/victronenergy/dynamic-ess/assets/139110412/73055b6d-8ffe-429c-884d-8821fadc4317)

**Comment by dirkjanfaber** [comment]
You are right. It should read: "Positive values represent the energy used from the item (opposite for negatives)" instead. That should become visible once the next update has been released (or you can change it yourself too in the _schedule graph_ node on line 53.
