### ISSUE TITLE
[Feature]: Variable fg - Maximum Grid Import power (in kW)

### ISSUE THREAD

**Issue by TomasVelPar** [victronenergy/dynamic-ess#56]
### Contact Details

tomas.velasco.parra@gmail.com

### Description

At least, in Spain depending on the time and day of the week in the Spanish market, two different powers can be contracted. 

![image](https://github.com/victronenergy/dynamic-ess/assets/87165691/9427d111-ccda-4091-97e1-7e5c4af7114c)

As you can see in the image, from Monday to Friday there is a period from 0 to 8 (power 1) and another from 8 to 0 (power 2). On weekends and holidays, power 1 is used.

Thanks

### Suggested Solution

 It will be nice to make the Dynamic ESS know this (making a weekly time table) to select the fg - maximum power available. 
For example one guy instalation could have at power2 contrated only 1 kw and at power 1 contracted 10 kw. This is because power 2 hour the price por each kw (not kwh) is really cheaper.

**Comment by dirkjanfaber** [comment]
In the Node-RED implementation this is not supported. However, fixed prices can be set in the (beta) VRM implementation.

See https://www.victronenergy.com/live/drafts:dynamic_ess for more info on that.
