### ISSUE TITLE
Question: settings ok?

### ISSUE THREAD

**Issue by Mableeker** [victronenergy/dynamic-ess#58]
I've installed version 0.1.2 but the schedule shows no charge or discharge activity this afternoon/ evening, while prices are right to do so. In remote console I see a status unknown, is that ok or should it be changed? ![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/28fb1424-96ad-4c45-af24-3187d5a36da1)
![image](https://github.com/victronenergy/dynamic-ess/assets/118760571/7fafffcf-a2d4-4335-9c50-5613c47fc11a)

**Comment by dirkjanfaber** [comment]
Status "unknown' is expected. (https://github.com/victronenergy/dynamic-ess#the-console-shows-dynamic-ess-mode-unknown). 

My guess about not charging and discharging is that it probably costs more to do so than it is to keep the batteries around the same level. Note that the aim for Dynamic ESS is not to trade with energy, but to minimize the overall costs. See the [about](https://github.com/victronenergy/dynamic-ess#about) section on the README.

**Comment by Mableeker** [comment]
Thanks, I missed that trouble shooting section, sorry. And I missed a typo in the sell formula. I was too hasty 🫢

Everything looks good now!

**Comment by dirkjanfaber** [comment]
No problem. Glad it got sorted!
