### ISSUE TITLE
[Bug?]: Why charging with the handbrakes on?

### ISSUE THREAD

**Issue by SimonYoungtree** [victronenergy/dynamic-ess#61]
### Contact Details

siempoot@gmail.com

### VRM / Site iD

c0619ab31cc4

### Country / region

Netherlands (nl)

### B max

40

### TB max

6

### FB max

6

### TG max

16

### FG max

16

### Battery costs

0.027

### Buy price

(p+0.13)*1.21+0.02

### Sell price

(p+0.13)*1.21-0.02

### feed-in possible

yes

### feed-in possible

None

### What happened?

A bug happened, (but it may also be a feature)! During midday, when the prices are lowest the system is charging, but at a limited speed. Is this limited speed a feature or a bug? If it is a feature, then what is the thought behind? (Perhaps to avoid losses in the Multiplus?)
![Screenshot 2023-09-14 133420](https://github.com/victronenergy/dynamic-ess/assets/139110412/ba87d17e-1790-4a70-b11d-e3b5fb1aa279)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
Have you checked [here](https://github.com/victronenergy/dynamic-ess/tree/main#the-battery-discharges-too-slow-to-keep-up-with-the-target-soc)?

The system needs to know your battery capacity in order to switch up gears.

**Comment by SimonYoungtree** [comment]
I did not see the 0.1.3 version yet. I was still on 0.1.2. Still charging is going up and down. Sometimes reaching max capacity (10A AC per Multiplus configured), but most of he times staying at 2/3rd. This may be by design. I do not know.
