### ISSUE TITLE
[Bug]: Error fetching VRM data

### ISSUE THREAD

**Issue by Edrettikketet** [victronenergy/dynamic-ess#62]
### Contact Details

e.peetam@aeromech.nl

### VRM / Site iD

222396

### Country / region

Netherlands (nl)

### B max

9.6

### TB max

5.0

### FB max

5.0

### TG max

5.75

### FG max

5.75

### Battery costs

0.08

### Buy price

(p+0.018+0.12599)*1.21

### Sell price

(p+0.018+0.12599)*1.21

### feed-in possible

yes

### feed-in possible

yes

### What happened?

A bug happened!
Somehow the node 'VRM dynamic ESS' stated that I filled out "invalid properties - invalid input pattern" and it points to the VRM-id.  I don't know why, but I'm sure it is identical to the site ID (after https://.
So what else can be the problem?

![image](https://github.com/victronenergy/dynamic-ess/assets/132836191/f4f65908-23d6-4a59-9ebe-312d6a383a99)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
The system has switched to using the VRM Portal id. See [here](https://github.com/victronenergy/dynamic-ess/blob/main/RELEASE-NOTES.md#general):

> Configuration no longer uses the site ID, but switched to the more common VRM portal ID (you can find that under the _Device list -> Gateway_ and then VRM portal ID).

It looks something like `c0619ab27f32 `.
