### ISSUE TITLE
[Bug]: Battery charging with full solar power

### ISSUE THREAD

**Issue by fofo444** [victronenergy/dynamic-ess#69]
### Contact Details

fofo444@gmail.com

### VRM portal ID

b827eb779d5c

### Country / region

Slovakia (sk)

### B max

14

### TB max

5

### FB max

5

### TG max

2.5

### FG max

2.5

### Battery costs

0.04

### Buy price

0.254

### Sell price

p

### feed-in possible

yes

### feed-in possible

yes

### What happened?

When battery charging is planned, it is with the full power of the solar panels and the appliances are powered from the grid. 
(Battery charging) = (Pv charger)  and (Grid) = (AC Loads)
It is rightly  (Battery charging) = (Pv charger) - (AC Loads) and (Grid) = 0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
Thanks for the report. We are looking into it. Do you have feed-in of excess DC coupled PV enabled on your system?

**Comment by fofo444** [comment]
![foto](https://github.com/victronenergy/dynamic-ess/assets/47315071/531d40c7-dd14-47c1-ac5a-4c4ae434a2cc)

**Comment by dirkjanfaber** [comment]
We've identified an issue in the underlying code, which will be resolved with the next candidate release.
