### ISSUE TITLE
[Feature]: minimum SOC

### ISSUE THREAD

**Issue by disaster123** [victronenergy/dynamic-ess#77]
### Contact Details

Github

### Description

I really would like to define a minimum SOC for battery. Currently it schedules the soc down to 3%

### Suggested Solution

Implement a setting to set the minimum expected SOC.

**Comment by dirkjanfaber** [comment]
The system already uses the minSOC set in the console under the ESS menu. It looks like that on your system it is set to 0.

<img width="495" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/f3d4f387-74a2-4f00-9a08-bd8c5980373a">
