### ISSUE TITLE
[Bug]: start to feed the battery from grid instead of waiting for pv / solar power

### ISSUE THREAD

**Issue by disaster123** [victronenergy/dynamic-ess#79]
### Contact Details

through github

### VRM portal ID

e45f019ec891

### Country / region

Germany (de)

### B max

10

### TB max

4

### FB max

4

### TG max

4

### FG max

4

### Battery costs

0.01

### Buy price

(p+0.1574)

### Sell price

0.07

### feed-in possible

no

### feed-in control

no

### Version

0.1.6

### What happened?

A bug happened!

See the attached pictures. dynamic ess started to feed / load the battery from grid instead of waiting for PV / solar power.

### Screenshots

![image0](https://github.com/victronenergy/dynamic-ess/assets/861558/e68aede2-abed-45c6-9af2-0f86ef43b8ed)
![image1](https://github.com/victronenergy/dynamic-ess/assets/861558/349ecc29-7de0-4d75-a6d4-8a7959257b01)
![image2](https://github.com/victronenergy/dynamic-ess/assets/861558/9b237ec9-fdb6-4814-94a1-098a0fe0a772)

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Marous23** [comment]
Same here. Even I am in specific time on higher % then scheduled „Targeted Soc“ system is against logic feeding the battery from grid.

**Comment by dirkjanfaber** [comment]
It seems there is less PV than forecasted so DESS plans to use the grid to meet the target SOC. So this is not a bug.
The forecasts will become more accurate once the system runs longer. At the moment your system only reported the data for a week.

**Comment by disaster123** [comment]
@dirkjanfaber mhm might be but the main problem seems that the wheather is not like it is reported. It's cloudy and rainy but the system says sunny:

![image](https://github.com/victronenergy/dynamic-ess/assets/861558/c621c1e0-e669-4e1c-b2fe-133e531961fa)

**Comment by dirkjanfaber** [comment]
The weather widget on the dashboard comes from a weather API, not solcast and no interdependence with DESS. So there is no linkage between those two.
But we are looking into why that widget was not matching reality on your system.
