### ISSUE TITLE
[VRM - Bug]: Grid pull 

### ISSUE THREAD

**Issue by h2009** [victronenergy/dynamic-ess#86]
### Contact Details

layth@layth.co.uk

### VRM portal ID

48e7da8580e7

### Country / region

None

### B max

76.8

### TB max

24

### FB max

18

### Battery costs

0

### Buy price

fixed uk octopus intelligence 

### feed-in possible

no

### feed-in control

no

### What happened?

Off-peak Tariff details: 00:00 to 05:00 - cost to charge from grid 7.5p 
Peak Tariff details: 05:00 to 11:59 - cost to charge from grid 41p 
Battery cost 0.00p 

The graph on today DESS, was showing 3x grid pulls at random times during the day when the batteries SOC was always above 60%; the system was looking to pull from the grid at peak rate. 
Load demand forecast (no more than 3kw). 

Using Node red to open the grid relay to prevent this action. 

Question: why the grid pulls at peak rate, when no battery cost and on peak tariff? Sorry no screenshots or why to look at previous data.

**Comment by dirkjanfaber** [comment]
The cause is described in [this manual](https://www.victronenergy.com/live/drafts:dynamic_ess):

> We keep the battery stable and not the grid: in our internal testing keeping the battery usage stable (basically the same as the plan) has been a lot more cost-effective than otherwise, because of the battery costs that pile up.
> Also keep in mind that, when doing a consumption forecast, the system does not known when during the hour that consumption will be done. If the forecast does not match the reality, Dynamic ESS does keep the planned battery usage stable while punishing the forecast inaccuracies on the grid (selling the excess to grid, buy the additional need from the grid). This can be less ideal, but it is an issue of the forecasts being inaccurate, nothing that the Dynamic ESS decided.

We are looking at ways to make the system behave better, but it is not that trivial to find a way that works for all systems.
