### ISSUE TITLE
[Bug]: No colour one some hours in energy graph

### ISSUE THREAD

**Issue by KajLehtinen** [victronenergy/dynamic-ess#88]
### Contact Details

kaj261@gmail.com

### VRM portal ID

d41243cd7f0b

### Country / region

Sweden - SE3 (se-3)

### B max

20

### TB max

5

### FB max

9

### TG max

2

### FG max

11

### Battery costs

0.0001

### Buy price

(p+0.027692+0.041281)*1.25

### Sell price

(p-0.02527+0.00)*1.25

### feed-in possible

yes

### feed-in control

yes

### Version

0.1.6

### What happened?

I got some hours that are white in the energy graph, see below

![image](https://github.com/victronenergy/dynamic-ess/assets/102818048/c7d700d3-87a4-491f-ac03-58971e95a7b3)

There is a white unlabeled section in the popup legend and only forecasts for PC yield and consumption is shown during some hours. The white section seems to equal the consumption forecast in the graph.

/Kaj  

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by KajLehtinen** [comment]
Looking at the Overviwe graph the system SoC is flat during most of the same time
![image](https://github.com/victronenergy/dynamic-ess/assets/102818048/25edb467-5570-466e-ad9e-44d3e3ef68f9)

And the Dynamic ESS schedule is locked to 63%

![image](https://github.com/victronenergy/dynamic-ess/assets/102818048/8d2a5ef6-a9ac-4f8f-b8d3-1c9e1139dc76)

**Comment by dirkjanfaber** [comment]
The white value is essentially the part below both of the lines (consumption and pv yield). The part between should be filled as well, but when price is below zero, things become special. We are looking into improving the graph in such cases.
