### ISSUE TITLE
[VRM - Bug]: day ahead prices are flat

### ISSUE THREAD

**Issue by Marous23** [victronenergy/dynamic-ess#89]
### Contact Details

marek.vagner@gmail.com

### VRM portal ID

c0619ab1ea67

### Country / region

Czech Republic (cz)

### B max

12

### TB max

12

### FB max

12

### TG max

17.25

### FG max

17.25

### Battery costs

0.04

### Buy price

(p+0.012+0.032)*1.21

### Sell price

(p-0.02+0.032)*1.21

### feed-in possible

yes

### feed-in control

yes

### What happened?

I am back testing the Dynamic ESS. This time the VRM implementation. This morning I wanted to check the graphs and it is strange but the prices are not loaded correctly. The graph is flat, totally different than the real one. The flat price was visible yesterday at evening too.  I am attaching a screen taken on my phone.
![IMG_5419](https://github.com/victronenergy/dynamic-ess/assets/144769966/3c6bc50b-42d5-4a4e-9332-c89eef0a0def)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by dirkjanfaber** [comment]
You have set the Dynamic ESS to be off right now. 

<img width="333" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/71faa9cd-a773-482f-8dcc-7f5c2cf3fd0d">

So set that to auto and it should become functional again.

**Comment by Marous23** [comment]
Yeah, I switched it off because I saw the graph with flat price, obviously broken. So I tought the plan based on broken price wont be good too. And it was showing just „Loading“.
Now I switched back to „auto“. But the price is still flat.
![IMG_5420](https://github.com/victronenergy/dynamic-ess/assets/144769966/0199e088-646c-4ca8-bb1d-6e168b919222)

**Comment by Marous23** [comment]
I see the current plan as „send all to grid and keep the battery flat“. 
<img width="1030" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/144769966/6b3db315-394e-4d4c-a526-e9144335e3ac">
That does not make sense in context the prices are currently almost zero.
<img width="802" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/144769966/c3ee9bd5-fbe4-47e7-9bb4-e2666c94e78f">
That confirms the loading of prices is broken and the derived plan too.

**Comment by dirkjanfaber** [comment]
Indeed. Can now confirm that there is a problem with the day ahead prices being fetched by the API. We are working on it.

**Comment by Marous23** [comment]
Perfect. Thanks. I believe it started already at yesterday evening.

**Comment by LecramRed** [comment]
Same here. Good to read that it's a known issue. The Node Red version works well.

**Comment by dirkjanfaber** [comment]
It should be back online now. We will be adding more monitoring to this part of the system. But as we are partly depending on third-party services (e.g. entsoe for the pricing), there is no guarantee that it won't happen ever again.

**Comment by Marous23** [comment]
Perfect. Thank you. I will try later today to switch to auto again. I understand it is problematic to rely on entsoe API. Any small change at their side and you are without data. If they are doing so it's inconsiderate of them.
Anyway thanks for your work. I am looking forward to later versions. I already switched to spot prices recently and I consider this kind of system like a must have. My first idea was to implement some light logic in Loxone myself. But it would take ages to test the ideas in real life and why to invent another wheel. So I am very happy that this is going to be a native feature of Victron system.
