### ISSUE TITLE
[Bug]: Target SOC 20% -> 10% is not being executed. No discharging

### ISSUE THREAD

**Issue by SimonYoungtree** [victronenergy/dynamic-ess#92]
### Contact Details

siempoot@gmail.com

### VRM portal ID

c0619ab31cc4

### Country / region

Netherlands (nl)

### B max

40

### TB max

6

### FB max

6

### TG max

16

### FG max

16

### Battery costs

0.027

### Buy price

(p+0.13)*1.21+0.02

### Sell price

(p+0.13)*1.21-0.02

### feed-in possible

yes

### feed-in control

None

### Version

0.1.6 - OS version 3.10-(with bugfix)

### What happened?

According schedule the Target SOC should go to 10% (now 20%), however we are now 45 minutes into that hour 8:45 and no discharging is taking place. Therefore DESS will not meet its plan

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

![image](https://github.com/victronenergy/dynamic-ess/assets/139110412/a5dfd33a-debe-49a0-82e6-b349b98ed3db)
![image](https://github.com/victronenergy/dynamic-ess/assets/139110412/59fccdd1-5572-4b66-9b72-70150256b4c5)
![image](https://github.com/victronenergy/dynamic-ess/assets/139110412/d86bd36a-39ee-4c5c-a7aa-a9971c27d5cc)

**Comment by dirkjanfaber** [comment]
Your minimum SOC right now is 20%. So it won't go below that, even if it would like to.

<img width="607" alt="image" src="https://github.com/victronenergy/dynamic-ess/assets/3098947/5ca1fb52-0cc3-4273-810d-92c974febc16">

**Comment by SimonYoungtree** [comment]
Where does this 20% come from? My min SOC is 10%:

![image](https://github.com/victronenergy/dynamic-ess/assets/139110412/5ecdfeff-6c27-4369-96d4-cacc6200657d)

**Comment by dirkjanfaber** [comment]
If you check under the _Dynamic ESS_ option (last item under _ESS_). What does it say there as minimum SOC?

**Comment by SimonYoungtree** [comment]
There is nothing shown about min. SOC. See new picture on GitHub.

Op vr 6 okt. 2023 10:57 schreef Dirk-Jan Faber ***@***.***>:

**Comment by dirkjanfaber** [comment]
Oh yeah, the console is not showing that min soc when running the Node-RED mode. 

You can see the value with this flow:
```
[{"id":"d8409391cd8338bf","type":"victron-input-custom","z":"15669bac1d63a856","service":"com.victronenergy.settings","path":"/Settings/DynamicEss/MinSoc","serviceObj":{"service":"com.victronenergy.settings","name":"com.victronenergy.settings"},"pathObj":{"path":"/Settings/DynamicEss/MinSoc","name":"/Settings/DynamicEss/MinSoc","type":"number"},"name":"","onlyChanges":false,"x":490,"y":1300,"wires":[["72b29acded57de34"]]},{"id":"72b29acded57de34","type":"debug","z":"15669bac1d63a856","name":"MinSoc","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":840,"y":1300,"wires":[]}]
```

**Comment by SimonYoungtree** [comment]
OK, used custom control to set it to 10%. Thanks
